-- Create sync_logs table to track all sync operations
create table public.sync_logs (
  id          bigint generated by default as identity primary key,
  synced_at   timestamptz not null default now(),
  mode        text not null check (mode in ('auto','manual')),
  duration_ms integer,
  entries_synced integer default 0,
  entries_updated integer default 0,
  entries_deleted integer default 0,
  error_message text
);

-- Create RPC function to get the latest successful sync timestamp
create or replace function public.get_latest_sync()
returns timestamptz
language sql stable security definer as $$
  select max(synced_at) from public.sync_logs where error_message is null;
$$;

-- Grant permissions
grant select on public.sync_logs to authenticated, anon;
grant execute on function public.get_latest_sync() to authenticated, anon; 